
<path> ::= <ident> ( ":" <ident> )*
<importdecl> ::= "imp" <path>

<fundef> ::= <fundecl> <body>
<fundecl> ::= "fun" <ident> ( <typename> <ident> "," )* ( <typename> <ident> )? ( "->" <typename> )? "extern"?

<structfields> ::= "{" ( <typename> <ident> "," )* ( <typename> <ident>? ) "}"

<typedef> ::= "type" ( "<" ( <ident> "," )* <ident>? ">" )? <ident> "=" (
    "{" ( <typename> <ident> "," )* ( <typename> <ident> )? "}",
    <typename>
    <typename> ( "|" <typename> )+
)

<stmt> ::= <callexpr> | <letstmt> | <retstmt> | <matchexpr> | <ifexpr> | "break" | "cont"

<matchcase> ::= <user-typename>  <ident>?
              | <literal>

<matcharm> ::= <matchcase>? "->" ( <expr> )
<matchexpr> ::= "match" <expr> "{" ( <matcharm> "," )* <matcharm>? "}"

<retstmt> ::= "return" <expr>?
<phistmt> ::= "phi" <expr>
<assignstmt> ::= <varstmt> "=" <expr>
<letstmt> ::= "let" ( "[" <typename> "]" )? <expr> ( '=' <expr> )?
<loopstmt> ::= "loop" <body>
<ifexpr> ::= "if" <expr> <body> ( ( "else" <body> ) | ( "else" <ifstmt> ) )

<body> ::= "{" <stmt>* "}"

<expr> ::= <primary-expr> ( <op> <expr> )?
<primary-expr> ::= <literal> | <prefix> | <op> <primary-expr>  | <ifexpr> | <matchexpr>
        | "$" <typename> <primary-expr>

<exprlist> ::= ( <expr> "," )* <expr>?

<prefixexpr> ::= <varaccessexpr> | <callexpr> | "(" <expr> ")" | <block>

<callexpr> ::= <prefixexpr> "." "(" <exprlist> ")"
<varaccessexpr> ::= <path>
                  | <prefixexpr> "[" <expr> "]"
                  | <prefixexpr> "." <ident>

<typename> ::= "bool" | "char" | "()"
             | ( "i" | "u" ) ( "8" | "16" | "32" | "64" )
             | "f" ( "32" | "64" )
             | <user-typename>
             | "*" <typename>
             | <array-typename>
             | "fun" "(" ( <typename> "," )* <typename>? ")" "->" <typename>
             | "(" <typename> ")"

<array-typename> ::= "[" <digit>+? "]" <typename>

<user-typename> ::= <path> ( "<" ( (<typename> "," )* <typename>? ) ">" )?

<literal> ::= <string-literal> | <bool-literal> | <char-literal> | <number-literal> | <array-literal>
            | <array-literal> | <tuple-literal> | <struct-literal>

<string-literal> ::= "\"" ( . | ( "\\" . ) )* "\""
<bool-literal> ::= "true" | "false"
<char-literal> ::= "'" ( . | "\\" . ) "'"
<array-literal> := "[" (<exprlist> "]"
<tuple-literal> ::+ "(" <exprlist> ")"
<struct-literal> ::= "#" <typename>? "{" ( <ident> "=" <expr> "," )* ( <ident> "=" <expr> )? "}"

<op> ::= "+" | "-" | "*" | "/" | "%" | "&" | "|" | "~" | "^" | "<" | ">" | "=="
       | "<=" | ">=" | "<<" | ">>" | "&&" | "||" | "!" | "!="

<number-literal> ::= <digit>+ "."? <digit>* ( "e" ( "+" | "-" ) <digit>+)?
                   | "0b" ( "0" | "1" )+
                   | "0x" ( <digit> | "a" | "b" | "c" | "d" | "e" | "f" )+
                   | "0o" ( "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" )+

<ident> ::= .+
<digit> ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
